# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AU4OgTkkUPKui-oEhU1LAr_8PQ4qCGRC
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

def analyze_numeric_column(df, column_name, target='Survived'):
    print(f"\n🔍 Summary statistics for '{column_name}':")
    print(df[column_name].describe())

    if target in df.columns:
        print(f"\n📊 Correlation with {target}: {df[[column_name, target]].corr().iloc[0,1]:.4f}")

    # Boxplot by Target if categorical
    if target in df.columns and df[target].nunique() <= 10:
        sns.boxplot(x=target, y=column_name, data=df)
        plt.title(f"Boxplot of {column_name} by {target}")
        plt.show()

    # Histogram with KDE
    sns.histplot(df[column_name].dropna(), kde=True, bins=30)
    plt.title(f"Distribution of {column_name}")
    plt.show()

    # Detect outliers using IQR
    Q1 = df[column_name].quantile(0.25)
    Q3 = df[column_name].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df[column_name] < Q1 - 1.5 * IQR) | (df[column_name] > Q3 + 1.5 * IQR)]
    print(f"\n⚠️ Outliers in {column_name}: {len(outliers)}")


def analyze_categorical_column(df, column_name, target='Survived'):
    print(f"\n🔍 Value counts for '{column_name}':")
    print(df[column_name].value_counts())

    if target in df.columns and df[target].nunique() <= 10:
        print(f"\n📈 Survival Rate by '{column_name}':")
        print(df.groupby(column_name)[target].mean())

        sns.barplot(x=column_name, y=target, data=df)
        plt.title(f"Survival Rate by {column_name}")
        plt.xticks(rotation=45)
        plt.show()

    sns.countplot(x=column_name, data=df)
    plt.title(f"Count of {column_name}")
    plt.xticks(rotation=45)
    plt.show()